# ========================
# Application
# ========================
spring.application.name=portfolio-tracker

# ========================
# Database (PostgreSQL)
# ========================
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio_dev
spring.datasource.username=or_d
spring.datasource.password=myStrongPass!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
# keeps schema updated without dropping data
spring.jpa.show-sql=true                   
# log SQL queries

# ========================
# Jackson (JSON serialization)
# ========================
spring.jackson.time-zone=Asia/Jerusalem
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ssXXX
spring.jackson.generator.write-bigdecimal-as-plain=true

# ========================
# SpringDoc / OpenAPI
# ========================
springdoc.override-with-generic-response=false

# ========================
# Actuator / Monitoring
# ========================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ========================
# API Keys
# ========================
price.alpha-vantage.api-key=9IGC4K8C7RC97FAR
# ========================
# Flyway
# ========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

